#!/bin/bash
set -e

# ============================================
# SFKT Bootstrap Node - Quick Setup Script
# ============================================
# Использование:
#   ./setup.sh                    # Интерактивный режим
#   ./setup.sh "vless://..."      # С ключом как аргументом
# ============================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_DIR/.env"

echo "=========================================="
echo "  SFKT Bootstrap Node - Quick Setup"
echo "=========================================="
echo ""

# Проверка root
if [ "$EUID" -ne 0 ]; then
    echo "ОШИБКА: Запустите скрипт от root"
    echo "  sudo $0 $@"
    exit 1
fi

# Получение VLESS ключа
VLESS_KEY="${1:-}"

if [ -z "$VLESS_KEY" ]; then
    echo "Введите VLESS ключ (начинается с vless://):"
    read -r VLESS_KEY
fi

# Проверка формата
if [[ ! "$VLESS_KEY" =~ ^vless:// ]]; then
    echo "ОШИБКА: Ключ должен начинаться с vless://"
    exit 1
fi

echo ""
echo "Парсинг ключа..."

# Парсинг VLESS URL
# Формат: vless://UUID@HOST:PORT?params#remark

# Извлечение UUID
UUID=$(echo "$VLESS_KEY" | sed -n 's|vless://\([^@]*\)@.*|\1|p')

# Извлечение HOST:PORT
HOST_PORT=$(echo "$VLESS_KEY" | sed -n 's|vless://[^@]*@\([^?]*\)?.*|\1|p')
HOST=$(echo "$HOST_PORT" | cut -d: -f1)
PORT=$(echo "$HOST_PORT" | cut -d: -f2)

# Извлечение параметров
PARAMS=$(echo "$VLESS_KEY" | sed -n 's|.*?\([^#]*\).*|\1|p')

# Парсинг параметров
get_param() {
    echo "$PARAMS" | tr '&' '\n' | grep "^$1=" | cut -d= -f2
}

SNI=$(get_param "sni")
PBK=$(get_param "pbk")
SID=$(get_param "sid")
PATH_PARAM=$(get_param "path")
FP=$(get_param "fp")

# Извлечение remark (название сервера)
REMARK=$(echo "$VLESS_KEY" | sed -n 's|.*#\(.*\)|\1|p' | sed 's/%20/ /g')

# Вывод распарсенных данных
echo ""
echo "Распарсенные данные:"
echo "  UUID:       $UUID"
echo "  Host:       $HOST"
echo "  Port:       $PORT"
echo "  SNI:        $SNI"
echo "  Public Key: ${PBK:0:20}..."
echo "  Short ID:   $SID"
echo "  Path:       $PATH_PARAM"
echo "  Remark:     $REMARK"
echo ""

# Проверка обязательных полей
if [ -z "$UUID" ] || [ -z "$HOST" ] || [ -z "$PBK" ] || [ -z "$SID" ]; then
    echo "ОШИБКА: Не удалось извлечь обязательные параметры из ключа"
    exit 1
fi

# Генерация приватного ключа (нужен для сервера)
echo "Генерация REALITY ключей..."
TEMP_KEYS="/tmp/xray_keys_$$.tmp"

if command -v xray &> /dev/null; then
    xray x25519 > "$TEMP_KEYS" 2>&1
elif command -v docker &> /dev/null; then
    docker run --rm teddysun/xray:latest xray x25519 > "$TEMP_KEYS" 2>&1
else
    echo "ОШИБКА: Нужен xray или docker для генерации ключей"
    exit 1
fi

PRIVATE_KEY=$(grep -iE "(privatekey|private key)" "$TEMP_KEYS" | grep -oE '[A-Za-z0-9_-]{43,44}' | head -1)
GENERATED_PUBLIC_KEY=$(grep -iE "(password|publickey|public key)" "$TEMP_KEYS" | grep -oE '[A-Za-z0-9_-]{43,44}' | head -1)
rm -f "$TEMP_KEYS"

echo "  Private Key: ${PRIVATE_KEY:0:20}..."
echo "  Public Key:  ${GENERATED_PUBLIC_KEY:0:20}..."
echo ""

# ВАЖНО: Public key из VLESS URL должен совпадать с тем что мы сгенерировали
# Но мы НЕ МОЖЕМ получить private key из public key
# Поэтому нужно использовать СВОИ ключи
echo "ВНИМАНИЕ: Генерируются НОВЫЕ ключи REALITY."
echo "Public key в VLESS ссылке на лендинге нужно обновить на:"
echo "  $GENERATED_PUBLIC_KEY"
echo ""

# Определение IP сервера
SERVER_IP=$(curl -s ifconfig.me || curl -s icanhazip.com || hostname -I | awk '{print $1}')
echo "IP сервера: $SERVER_IP"
echo ""

# Создание .env файла
echo "Создание .env файла..."
cat > "$ENV_FILE" << EOF
# ========================================
# Bootstrap Node Configuration
# Generated by setup.sh
# ========================================

NODE_ID=
NODE_NAME=$REMARK
NODE_HOSTNAME=$HOST
NODE_IP=$SERVER_IP
NODE_PORT=${PORT:-443}

NODE_COUNTRY=Russia
NODE_COUNTRY_CODE=RU
NODE_CITY=

# REALITY Keys
REALITY_PRIVATE_KEY=$PRIVATE_KEY
REALITY_PUBLIC_KEY=$GENERATED_PUBLIC_KEY
REALITY_SHORT_ID=$SID

# Shared UUID for all users
SHARED_UUID=$UUID

# SNI
NODE_SNI=${SNI:-max.ru}

# Main Server (для мониторинга)
MAIN_SERVER_URL=https://sfkt.mxl.wtf
NODE_API_KEY=

# Intervals
HEALTH_CHECK_INTERVAL=60
EOF

echo "  Создан: $ENV_FILE"
echo ""

# Обновление конфига Xray
echo "Обновление Xray конфигурации..."

CONFIG_FILE="/usr/local/etc/xray/config.json"
TEMPLATE_FILE="$REPO_DIR/config/xray_config.json"

# Установка Xray если не установлен
if ! command -v xray &> /dev/null; then
    echo "Установка Xray..."
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u root
fi

# Создание директорий
mkdir -p /usr/local/etc/xray
mkdir -p /var/log/xray

# Копирование и обновление конфига
cp "$TEMPLATE_FILE" "$CONFIG_FILE"

# Замена плейсхолдеров
sed -i "s/PRIVATE_KEY_PLACEHOLDER/$PRIVATE_KEY/g" "$CONFIG_FILE"
sed -i "s/SHORT_ID_PLACEHOLDER/$SID/g" "$CONFIG_FILE"
sed -i "s/SHARED_UUID_PLACEHOLDER/$UUID/g" "$CONFIG_FILE"

# Валидация конфига
echo "Проверка конфигурации..."
if ! xray run -test -config "$CONFIG_FILE" > /dev/null 2>&1; then
    echo "ОШИБКА: Конфигурация невалидна!"
    xray run -test -config "$CONFIG_FILE"
    exit 1
fi

echo "  Конфигурация OK"
echo ""

# Запуск Xray
echo "Запуск Xray..."
systemctl enable xray
systemctl restart xray
sleep 2

if systemctl is-active --quiet xray; then
    echo "  Xray запущен успешно!"
else
    echo "ОШИБКА: Xray не запустился"
    journalctl -u xray -n 20
    exit 1
fi

# Создание docker network
echo ""
echo "Подготовка Docker..."
docker network create sfkt_network 2>/dev/null || true

# Запуск node agent (опционально)
echo ""
echo "=========================================="
echo "  УСТАНОВКА ЗАВЕРШЕНА!"
echo "=========================================="
echo ""
echo "Xray работает на порту ${PORT:-443}"
echo ""
echo "ВАЖНО! Обновите VLESS ключ на лендинге:"
echo ""
echo "Новый Public Key:"
echo "  $GENERATED_PUBLIC_KEY"
echo ""
echo "Новый VLESS ключ:"
echo "  vless://$UUID@$HOST:${PORT:-443}?type=xhttp&security=reality&sni=${SNI:-max.ru}&fp=${FP:-chrome}&pbk=$GENERATED_PUBLIC_KEY&sid=$SID&path=${PATH_PARAM:-/sfkt-free}#$(echo "$REMARK" | sed 's/ /%20/g')"
echo ""
echo "Для запуска мониторинга (опционально):"
echo "  1. Добавьте NODE_API_KEY в .env"
echo "  2. docker compose up -d"
echo ""
